### ISSUE TITLE
TypeError: Cannot delete property '48' of [object String]

### ISSUE THREAD

**Issue by sdaitzman** [nbqx/extendscript-stream#1]
```
/Users/sam/Documents/projects/ai-random-color-variants/node_modules/temporary/lib/detector.js:23

  var last = Array.prototype.pop.apply(path);
                                 ^

TypeError: Cannot delete property '48' of [object String]
    at String.pop (<anonymous>)
    at normalize (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/temporary/lib/detector.js:23:34)
    at Object.detector.tmp (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/temporary/lib/detector.js:54:10)
    at Object.generator.build (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/temporary/lib/generator.js:45:27)
    at File.Base.init (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/temporary/lib/base.js:31:28)
    at new File (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/temporary/lib/file.js:23:8)
    at createJsx (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/fakestk/lib/executor.js:12:13)
    at module.exports (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/fakestk/lib/executor.js:42:13)
    at Object.exports.run (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/fakestk/lib/index.js:5:3)
    at ExtendScriptTransformStream._transform (/Users/sam/Documents/projects/ai-random-color-variants/node_modules/extendscript-stream/index.js:36:11)
```

**Comment by developersmd** [comment]
I have the same error..
